apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-events
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    push-event:                    # handles push events
      endpoint: /github            # 👈 same URL for both push + PR
      port: "12000"
      events:
        - push
      apiToken:
        name: github-secret
        key: token
      owner: Zeta201
      repository: microsmack

    pull-request-event:            # handles PR events
      endpoint: /github            # 👈 same URL
      port: "12000"
      events:
        - pull_request
      apiToken:
        name: github-secret
        key: token
      owner: Zeta201
      repository: microsmack
